# Site settings
title: Jaime Arias
email: arias@lipn.univ-paris13.fr
description: CNRS Research Engineer
timezone: Europe/Paris
encoding: utf-8
baseurl: ""
# url: "/" # for development
url: "https://www.jaime-arias.fr"

# Build settings
markdown: kramdown
exclude: ["README.md"]

# information
position: CNRS Research Engineer
telephone: +33 01 49 40 40 67
website: www.jaime-arias.fr
