# Site settings
title: Jaime Arias
email: arias@lipn.univ-paris13.fr
description: My personal website
timezone: Europe/Paris
encoding: utf-8
baseurl: "/site"
url: "/"

# Build settings
markdown: kramdown
exclude: ["README.md"]

# information
position: CNRS Research Engineer
telephone: +33 01 49 40 40 67
website: www.jaime-arias.fr
